### ISSUE TITLE
effect object in ioBroker not working

### ISSUE THREAD

**Issue by ricosander** [DrozmotiX/ioBroker.esphome#102]
Changing the effect in ioBroker Object of the device, it is not working:

![image](https://user-images.githubusercontent.com/61231999/125121172-cb743f00-e0f3-11eb-8144-01058fb266bf.png)

Changing 

- state
- blue
- brightness
- white
- etc. 
IS working. Except effect.

Using:

- ESP32 DevKit with a WS2812B (SK6812) Ring.
- NeoPixelBus@2.6.3

ESP yaml excerpt:
```
light:
  - platform: neopixelbus
    id: light_ring
    internal: False
    type: GRBW
    variant: SK6812 #WS2812X
    pin: GPIO5
    num_leds: "12"
    method: ESP32_I2S_1
    name: "LED Ring"
    effects:
      - addressable_scan:
      - addressable_color_wipe:
      - addressable_rainbow:
      - addressable_fireworks:
```

When starting the effect via boot on the esp device itself it works. The effect is also listed in the effectslist object.

```
on_boot:
--
  | priority: -10
  | then:
  | - light.turn_on:
  | id: light_ring
  | brightness: 40%
  | effect: "Scan"
```
