### ISSUE TITLE
Support for Displays

### ISSUE THREAD

**Issue by ahnungsbefreit** [DrozmotiX/ioBroker.esphome#103]
ESPHome Integration in ioBroker is already working very nicely and my preferred platform for new devices. However, the missing ability to use displays and send text to be displayed directly from ioBroker is one of the few features I am really missing for now.

Example:

`# SSD1306 Display 

font:
  - file: "LiberationSans-Regular.ttf"
    id: font1
    size: 20
    
  - file: "LiberationSans-Regular.ttf"
    id: font2
    size: 14

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    lambda: |-
      it.printf(64, 0, id(font1), TextAlign::TOP_CENTER, "Wetter");
      
      // Print temperature 
      if (id(temperature).has_state()) {
        it.printf(100, 20, id(font1), TextAlign::TOP_RIGHT , "%.1f°", id(temperature).state);
      }

      // Print humidity
      if (id(humidity).has_state()) {
        it.printf(100, 40, id(font1), TextAlign::TOP_RIGHT , "%.1f%%", id(humidity).state);
      }`

In this example I am using a lambda to display values of sensors connected to the same ESP. But if the value could be populated directly via MQTT it would be even more flexible. For the fonts, we might go with one predefined font for now and add selection of fonts later.

**Comment by DutchmanNL** [comment]
I need to get a display here to get this working :)

**Comment by DutchmanNL** [comment]
> In this example I am using a lambda to display values of sensors connected to the same ESP. But if the value could be populated directly via MQTT it would be even more flexible. For the fonts, we might go with one predefined font for now and add selection of fonts later.

looking at it, this should already be possible but you have to define an input.....!
Example : 

```
sensor:
  - platform: ...
    # ...
    id: my_sensor

display:
  - platform: ...
    # ...
    lambda: |-
      it.printf(0, 0, id(my_font), "The sensor value is: %.1f", id(my_sensor).state);
      // If the sensor has the value 30.02, the result will be: "The sensor value is: 30.0"
```

as you assig a id to that sensor (which could be any input) you can also use that to create a state for ioBroker, so I assume but using a text-sensor, or state you can use that with an action to show on the display ?
