### ISSUE TITLE
ESPHome client  TypeError: Cannot read properties of undefined (reading 'deserializeBinary')

### ISSUE THREAD

**Issue by Trrw** [DrozmotiX/ioBroker.esphome#136]
Ich wollte einen mmWave Sensor nachbauen. Dort habe ich folgendes Script verwendet:

https://gist.github.com/EverythingSmartHome/4f8c9d8e94bffb44c7b7965f172b6470

In HomeAssistant werden alle Werte ausgegeben. Im ioBroker erscheint folgende Fehlermeldung:

`ESPHome client 192.168.178.172 TypeError: Cannot read properties of undefined (reading 'deserializeBinary')`

Die Datenpunkte werden nicht erzeugt. Liegt es an der yaml oder ist das evtl ein Bug?

<img width="1696" alt="Bildschirmfoto 2022-08-16 um 19 54 44" src="https://user-images.githubusercontent.com/24519230/184946708-516e5f03-6760-4478-b090-1d4e487fb51d.png">
<img width="1045" alt="Bildschirmfoto 2022-08-16 um 19 54 56" src="https://user-images.githubusercontent.com/24519230/184946718-5fd72126-017b-493c-b1da-e5e32ec4c0dc.png">
<img width="1902" alt="Bildschirmfoto 2022-08-16 um 19 55 20" src="https://user-images.githubusercontent.com/24519230/184946728-d61b9611-d90e-4061-a001-2ecb2f0f6313.png">

**Comment by Trrw** [comment]
Also es liegt definitiv an diesen Zeilen:

Also es liegt definitiv an diesen Zeilen. HomeAssistant verbindet sich und dort ist alles gut. IoBroker mag irgendwas nicht und kappt die Verbindung:
```
number:
  - platform: template
    name: distance
    id: distance
    min_value: 0
    max_value: 1350
    initial_value: 315
    optimistic: true
    step: 15
    restore_value: true
    unit_of_measurement: cm
    mode: box
    set_action:
      - switch.turn_off: mmwave_sensor
      - delay: 1s
      - uart.write: !lambda
                      int cm = (int)ceil(x / 15.0);
                      std::string cms = "detRangeCfg -1 0 " + to_string(cm);
                      return std::vector<unsigned char>(cms.begin(), cms.end());
      - delay: 1s
      - uart.write: "saveCfg 0x45670123 0xCDEF89AB 0x956128C6 0xDF54AC89"
      - delay: 1s
      - switch.turn_on: mmwave_sensor  
      
  - platform: template
    name: latency
    id: latency
    min_value: 0
    max_value: 65000
    initial_value: 12500
    optimistic: true
    step: 25
    restore_value: true
    unit_of_measurement: ms
    mode: box
    set_action:
      - switch.turn_off: mmwave_sensor
      - delay: 1s
      - uart.write: !lambda
                      int ms = (int)ceil(x / 25.0);
                      std::string mss = "outputLatency -1 0 " + to_string(ms);
                      return std::vector<unsigned char>(mss.begin(), mss.end());
      - delay: 1s
      - uart.write: "saveCfg 0x45670123 0xCDEF89AB 0x956128C6 0xDF54AC89"
      - delay: 1s
      - switch.turn_on: mmwave_sensor    

  - platform: template
    name: sensitivity
    id: sensitivity
    min_value: 0
    max_value: 9
    initial_value: 7
    optimistic: true
    step: 1
    restore_value: true
    set_action:
      - switch.turn_off: mmwave_sensor
      - delay: 1s
      - uart.write: !lambda
                      std::string mss = "setSensitivity " + to_string((int)x);
                      return std::vector<unsigned char>(mss.begin(), mss.end());
      - delay: 1s
      - uart.write: "saveConfig"
      - delay: 1s
      - switch.turn_on: mmwave_sensor
```

**Comment by Trrw** [comment]
Kann es sein, dass der Bug bei number: platform: template liegt?
```
number:
  - platform: template
```

Ich habe ein leeres Projekt erstellt. Aus der Doku https://esphome.io/components/number/template.html das Beispiel entnommen. Sobald dies eingefügt ist, wird die Verbindung zum ioBroker geschlossen.

```
esphome:
  name: "1"

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "XXXXXX"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "1 Fallback Hotspot"
    password: "XXXXXXX"

substitutions:
  device_name: TEST
  
number:
  - platform: template
    name: Template number
    optimistic: true
    min_value: 0
    max_value: 100
    step: 1
    
```
