### ISSUE TITLE
WEMOS D1 Mini|fatal error: ESPAsyncWebServer.h: No such file or directory 

### ISSUE THREAD

**Issue by Maschine20** [DrozmotiX/ioBroker.esphome#145]
**Describe the bug**  
In the Dashboard I have edited the yaml and then pressed save and install. Then the installation failed.
I use this yaml also for an other wemos d1 mini and it is working (only diffrent name).

YAML:
```
esphome:
  name: esphome-web-106b5d
  platform: esp8266
  board: nodemcuv2

#Enable logging
logger:

# Enable Home Assistant API
api:

ota:


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Esphome-Web-106B5D"
    password: "6EwDGxOt4jTs"

captive_portal:
# Example configuration entry
```

After pressing install i got following message:

```
INFO Reading configuration /opt/iobroker/iobroker-data/esphome.0/esphome-web-106b5d.yaml...
INFO Generating C++ source...
INFO Compiling app...
Processing esphome-web-106b5d (board: nodemcuv2; framework: arduino; platform: platformio/espressif8266 @ 3.2.0)
--------------------------------------------------------------------------------
HARDWARE: ESP8266 80MHz, 80KB RAM, 4MB Flash
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
Library Manager: Installing ottowinter/ESPAsyncTCP-esphome @ 1.2.3
Warning! Please upgrade to the PlatformIO Core 6
Library Manager: Installing esphome/ESPAsyncWebServer-esphome @ 2.1.0
Warning! Please upgrade to the PlatformIO Core 6
Dependency Graph
|-- <DNSServer> 1.1.1
|-- <ESP8266WiFi> 1.0
|-- <ESP8266mDNS> 1.2
Compiling .pioenvs/esphome-web-106b5d/src/esphome/components/captive_portal/captive_portal.cpp.o
Compiling .pioenvs/esphome-web-106b5d/src/esphome/components/esp8266/preferences.cpp.o
In file included from src/esphome/components/captive_portal/captive_portal.h:10,
                 from src/esphome/components/captive_portal/captive_portal.cpp:3:
src/esphome/components/web_server_base/web_server_base.h:9:10: fatal error: ESPAsyncWebServer.h: No such file or directory

***************************************************************************
* Looking for ESPAsyncWebServer.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:ESPAsyncWebServer.h"
* Web  > https://registry.platformio.org/search?q=header:ESPAsyncWebServer.h
*
***************************************************************************

    9 | #include <ESPAsyncWebServer.h>
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
*** [.pioenvs/esphome-web-106b5d/src/esphome/components/captive_portal/captive_portal.cpp.o] Error 1
========================== [FAILED] Took 3.22 seconds ==========================
```

**Versions:**  
 - Adapter version: v0.2.4
 - JS-Controller version: 4.0.23
 - Node version: 16.16.0 
 - Operating system: ubuntu Proxmox

Any idea what i can do or what i ve made wrong?
