### ISSUE TITLE
Fields which are dropdowns in esp cant be edited

### ISSUE THREAD

**Issue by volkerrichert** [DrozmotiX/ioBroker.esphome#146]
**Describe wanted Enhancement !**  
I'd like to have to have ESPhome drop downs, like pulse, being editable (as drop down?) and pushed to device.

**Why should we put effort in it ?**  
Yo can not change them in iobroker. The are shown correctly, but editing them will not result in a chage.

**Additional context**  
yaml example:
```
light:
  # ... and then make a light out of it.
  - platform: monochromatic
    name: "${device_name} Green LED"
    output: s26_green_led
    effects:
    - pulse:
    - pulse:
        name: "Fast Pulse"
        transition_length: 0.5s
        update_interval: 0.5s
    - pulse:
          name: "Slow Pulse"
          # transition_length: 1s      # defaults to 1s
          update_interval: 2s
```

object definition of generated state in iob
```
{
  "type": "state",
  "common": {
    "modify": "",
    "name": "effect of wohnzimmer-tv Green LED",
    "type": "string",
    "role": "state",
    "read": true,
    "unit": "",
    "write": true
  },
  "from": "system.adapter.esphome.0",
  "user": "system.user.admin",
  "ts": 1670423998716,
  "_id": "esphome.0.4855194680A1.Light.3747644526.effect",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

the `effectList` inside the config shows "["None","Pulse","Fast Pulse","Slow Pulse"]" as value
