### ISSUE TITLE
Adding Type "Select" to ESP Home Adapter

### ISSUE THREAD

**Issue by patricknitsch** [DrozmotiX/ioBroker.esphome#169]
Beca or Koenighaus thermostats with Tuya Protocol send a datapoint from type ENUM. This datapoint has these values: 0: Manual, 1: Schedule and on Koenighaus 2: Holiday.

```
select:
  # Mode
  - platform: "tuya"
    #name: Schedules
    internal: true
    id: mode
    icon: "mdi:calendar"
    enum_datapoint: 4
    options:
      0: Manual
      1: Schedule
      2: Holiday -> only for Koenighaus
    on_value:
        - script.execute: switching
```

@DutchmanNL : Is there an opinion to integrate the select mode in the ESP Home Adapter?

Many thanks for supporting.
