### ISSUE TITLE
Hinzufügen von ESP32 Kameras

### ISSUE THREAD

**Issue by ali86x** [DrozmotiX/ioBroker.esphome#243]
Vielleicht kann sich dem Thema ja jemand annehmen,

Wenn noch weitere Infos benötigt werden, einfach fragen und ich versuche alles bereitzustellen

**!!! Before you start !!!!**
- [x ] I have verified that there is not already an issue requesting the same Enhancement
- [x ] Is it about adding support for a new device-type?

**Describe wanted Enhancement !**  
Add support for ESP32cam

```yaml
esphome:
  name: xiaosense1
  friendly_name: XiaoSense1
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio 

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "...."

ota:
  - platform: esphome
    password: "89801c347be3c83f18346f6b51e6dd73"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiaosense1 Fallback Hotspot"
    password: "1234567890"

captive_portal:

# Configuration for the ESP32 Camera
esp32_camera:
  id: espcam
  name: My Camera
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  resolution: 800x600
  
# Configuration for the ESP32 Camera Web Server
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot    
```

**Auszug aus Warnmeldung im Log**  
```
2025-05-29 13:33:48.469 - warn: esphome.0 (1716224) DeviceType Camera not yet supported
--
2025-05-29 13:33:48.469 - warn: esphome.0 (1716224) Please submit git issue with all information from next line
2025-05-29 13:33:48.470 - warn: esphome.0 (1716224) DeviceType Camera \| State-Keys {"key":199845799,"data":"/9j/4AAQSkZJRgABAQEAAAAAAAD/2wBDAAoHCAkIBgoJCAkLCwoMDxkQDw4ODx8WFxIZJCAmJiQgIyIoLToxKCs2KyIjMkQzNjs9QEFAJzBHTEY/Szo/QD7/2wBDAQsLCw8NDx0QEB0+KSMpPj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj4+Pj7/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/wAARCAJYAyADASEAAhEBAxEB/9oADAMBAAIRAxEAPwDiMndSNhh/FkA45rqd+5hbsQjds2knp/u4pvf7zYx61XOaaCq3Tml3e5qG2RPsOLsPxHeheB1z9ajma0F5IaPl7t+LUZPH901fvFWEOT1JxSEfLhM9eaSYbB2PzUgkbGetHMIN209T+dJvGfvNU3kU9hd5FDScVPUSQu/60u5+ma0DQXJFKWymMnd+lQ+4Cbs0jGhXZcWOoJqfIVxPekVsrn8qrfYadgY8U3Hy1Nxmt4anxfzxuiPug+TdGrYwea6JZef9XDn/AK5LXHiKSlPUPaTXUlSXn/VQf9+VpftXzf6q3/78JXP9Xp9UP21RdSxDc/N/qbf/AL8JVxbkdPJtf/AdKzlg6PYHiKn8xIJf+mNr/wCA0dRMcN/qbb/wHSksNS/lG69T+YhmkPP7m29v9HSqU/Kn5IvwiWr+r0+wva1O5AJtjf6qD/vytWorv5v9VbdM/wDHtHVPD0+wKvU7mrY3mdytDZ+v/HrHT5Zv+mFp/wCAsdZfU6N78pf1mq/tGddHp+6tv/AdKxrpGeJsxxfhGoreFGnHoZyqTe7OYma706+S6gCHyz92WMFTXpGi6tHqumfaYbez+X5ZB9jj4IxmrxWHp1VzSVy415xVosnkct/ywtP/AAFjqhdc/wDLK3/CBK5o4aj/ACideo/tGBqdoZB58Xlb0B+TaADWbHc7lYKIt69vLFdkKcbbGblJdSWy8TXFp8s9nZzD/Zt4lNdTY30Wp2omtFtHT+IC3T5T6VjWwdLdItYmr/MZuv6umlSiCJIZLx1zs2LhKwf+Eg1ESZk+yle4WAVrTwtNdCeeT1bNGx1GK9GAfLuD/wAszyWrQSU4+YVNSCHcjmihuBiTef8AdkZK53UdOltSX/0vyB/y0884renUlHRMlwj1RQYED/Wz/wDf5qgkDf8APWb/AL+tXTTrVP5ifZQ/lI/Kbruk/wC+jUZQ/wB5/wDvs1ft5PqHIB6dW/OkDEUlOQJBz1yfzpOf7xp8zHoLn3NNJ9zS5mKwpY+poBPaiw==","done":false} \| [entityStateConfig] {"config":{"objectId":"my_camera","key":199845799,"name":"My Camera","uniqueId":"xiaosense1cameramy_camera","disabledByDefault":false,"icon":"","entityCategory":0},"name":"My Camera","type":"Camera","unit":""}

```

**Comment by SimonFischer04** [comment]
> Einstellungen sind soweit ich weiss keine möglich (leider, sowas wie Flip, rotate oder Auflösung ändern geht ja nur durch neue Config).

Dacht ich mir doch, nachdem ich kurz die Component Docs gelesen hab 🙂

> Vielleicht kann einfach nur die Warnmeldung rausnehmen.

Bin eher ein Freund von mehr Meldungen als weniger, vor allem wenn sie eh nur 1mal beim Start kommt.
Sonst fragen nur wieder User "warum ist da kein object" ...

Normal braucht Kamera eh schon recht viel Ressourcen und man wird an den esps mit camera jetzt nicht noch zig sensoren dran haengen haben.
Und wenn der eh nur camera spielt, kann man ihn auch einfach gar nicht mit dem Adapter verbinden, wenn man eh nix damit machen kann.

> Man KÖNNTE noch Dinge integrieren wie:
> Datenpunkte mit URL zu Stream und snapshot inklusive IP Adresse, Kamera-ID bzw Name, Auflösung, Zeitpunkt der letzen Aufnahme etc.

Kommen die auch per Protocoll / Wird da irgenwas am web_server angezeigt?
Der Adapter verwendet die Native API um Daten abzuholfen: https://www.esphome.io/components/api. Implementiert in js von: https://github.com/twocolors/esphome-native-api

Falls das da nicht rauskommt wuerd ich da nur ungern reinpfuschen und manuell weitere Datenpunkte anlegen. Vor allem fuer statische Werte wie eine URL....
Weiters geht das auch nicht mal so einfach. Woher soll der Adapter wissen welchen port du fuer den Stream konfiguriert hast, ...
Dafuer eine extra config option im Adapter zu machen, nur um dann 1mal eine URL in ein object zu schreiben - seh ich schon als sehr speziell an ...

> Den Kamera-Adapter kannte ich nicht, sieht aber interessant aus. Ich brauche im Grunde nur die Snapshots, das klappt mit Blockly und wget ganz gut.
> Aber danke für den Tipp.

OK, np, gern geschehen.

**Comment by SimonFischer04** [comment]
> Ich plane an jede Kamera auch einen Temperatur und Feuchtigkeitssensor anzuschließen.
Die werden aber ja eh dann als separate Entitäten vom Adapter erkannt

👍, für einen Sensor wirds vermutlich passen.


> Ich versuche mal das rauszufinden, aber dafür bin ich wahrscheinlich eher zu unerfahren in dem Thema.

Am einfachsten mal 
```
web_server:
```
Component zum yaml hinzufügen und dann im browser ip vom esp eingeben und mal schaun was dort so alles gibt.

> Die Ports und die ID könnte man z.b. aus der Config auslesen, falls der Adapter da Zugriff drauf hat.

Zu so ähnlichen Interaktionen bei anderen Componenten gabs schon ein paar mal fragen.
In dem Setup wäre es grundsätzlich möglich die config files die das Dashboard speichert auch im Adapter zu lesen / verarbeiten.

Grundsätzlich ist das Dashboard aber eine komplett eigenständige Anwendung. Wird nur aus convenience aus im Adapter Tab als iframe eingebunden. 
(Und speichert halt die Files am gleichen Geräte -> könnte man hier wieder lesen)

Aber 1. ob sich der Aufwand lohnt: initial und auch mögliche updates von esphome, die files wieder inkompatibel machen und der Adapter Anpassungen braucht.
Ein Programm A (iobroker Adapter) sollte normal nicht in Files eines anderen Programms B  (esphome dashboard. Wird von anderen entwickelt) eingreifen, dass führt früher oder später nur zu Problemen.

2. Wenn das Dashboard auf einem externen System betrieben wird - was der Adapter auch unterstützt - ist es aus mir Zugriff auf die Konfigs, dann ist das ganze nicht mal mehr möglich.

**Comment by SimonFischer04** [comment]
> sieht dann halt nicht so leer aus.

Und falls dir nur drum geht das der objekt baum voller ist: 
kannst auch gern selber random Objekte erstellen. Ps: keine Garantie auf Funktion und Überleben dieser, wenn sie innerhalb vom esphome sind. 😂.

Jokes aside: Das ist für mich keine valide Begründung für extra Ressourcenbedarf

**Comment by ali86x** [comment]
Ich habe mal den webserver mit implementiert.
Wie schon erwartet, gibt es auch hier nichts wirklich zur Kamera.

![Image](https://github.com/user-attachments/assets/bc8cad58-ee66-4073-b763-ba99a1628847)

Aktuelle yaml:
```yaml
esphome:
  name: xiaosense1
  friendly_name: XiaoSense1
  platformio_options:
    build_flags: -DBOARD_HAS_PSRAM
    board_build.arduino.memory_type: qio_opi
    board_build.f_flash: 80000000L
    board_build.flash_mode: qio 

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "..."

ota:
  - platform: esphome
    password: "..."

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Xiaosense1 Fallback Hotspot"
    password: "1234567890"

captive_portal:

# Configuration for the ESP32 Camera
esp32_camera:
  id: espcam
  name: My Camera
  external_clock:
    pin: GPIO10
    frequency: 20MHz
  i2c_pins:
    sda: GPIO40
    scl: GPIO39
  data_pins: [GPIO15, GPIO17, GPIO18, GPIO16, GPIO14, GPIO12, GPIO11, GPIO48]
  vsync_pin: GPIO38
  href_pin: GPIO47
  pixel_clock_pin: GPIO13
  resolution: 1024x768
  
# Configuration for the ESP32 Camera Web Server
esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot    

# I2C configuration
i2c:
  sda: GPIO5
  scl: GPIO6

# SHT3X config
sensor:
  - platform: sht3xd
    temperature:
      name: "Temperatur"
    humidity:
      name: "Luftfeuchtigkeit"
    address: 0x44
    update_interval: 60s

# Webserver zum testen
web_server:
  port: 81
````

Also wird es wohl so bleiben müssen wie es jetzt ist.
Ich kann verstehen, dass der Aufwand da was um mehrere Ecken jetzt reinzubringen zu groß ist bzw, das Fehlerpotential zu groß ist.

Eins vielleicht noch für die Optik:
Anstatt der Warnung "DeviceType Camera not yet supported" vielleicht etwas wie "DeviceType Camera recognized, but no datapoints created."
Oder so.

Danke für den Rat und die Unterstützung.
