### ISSUE TITLE
Support HA (Sensor) Platform / Dedicated iobroker platform.

### ISSUE THREAD

**Issue by SimonFischer04** [DrozmotiX/ioBroker.esphome#251]
**!!! Before you start !!!!**
- [X] I have verified that there is not already an issue requesting the same Enhancement
- [X] Is it about adding support for a new device-type?

**Describe wanted Enhancement !**  
Support the homeassistant plattform and / or create a new iobroker platform in esphome itself.

**Why should we put effort in it ?**  
Easily import state from iobroker into esphome ecosystem.

**Example YAML**  
If applicable, example yaml that demonstrates / can be used to test the new proposed functionality.  
Just an example, insert you own yaml!:
```yaml
# Example configuration entry
sensor:
  - platform: homeassistant
    name: "Temperature Sensor From Home Assistant"
    entity_id: sensor.temperature_sensor
```

**Additional context**  
- See support issue in used library: https://github.com/Nafaya/esphome-native-api/issues/17
